# Importación de librerías

In [2]:
import pandas as pd

# Ingesta de datos

In [3]:
archivo_excel = pd.ExcelFile("..\data\INSUMOS OPERACIONALES STOCK RELIX.xlsx")
print("Hojas disponibles:", archivo_excel.sheet_names)

Hojas disponibles: ['Insumos Operacionales 2025', 'INGRESO', 'SALIDA', 'STOCK ']

In [4]:
insumos = pd.read_excel("..\data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='Insumos Operacionales 2025', skiprows=7)

In [5]:
insumos.head()

,Unnamed: 0,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES,Unnamed: 7
0,NaN,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN,NaN
1,NaN,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN,NaN
2,NaN,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN,NaN
3,NaN,1.4,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ...",PIPING,UN,NaN,NaN
4,NaN,1.5,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,NaN,NaN

In [6]:
# Se eliminan columnas innecesarias dentro del archivo
insumos = insumos.drop(insumos.columns[[0, 7]], axis=1)
insumos.head()

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
0,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN
1,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN
2,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN
3,1.4,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ...",PIPING,UN,NaN
4,1.5,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,NaN

In [7]:
insumos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ITEM                       490 non-null    float64
 1   CODIGO SAP/OTRO            490 non-null    object
 2   DESCRIPCION DEL MATERIAL   490 non-null    object
 3   CLASIFICACIÓN              490 non-null    object
 4   U M                        486 non-null    object
 5   OBSERVACIONES              0 non-null      float64
dtypes: float64(2), object(4)
memory usage: 23.1+ KB

In [8]:
insumos.columns

Index(['ITEM', 'CODIGO SAP/OTRO', 'DESCRIPCION DEL MATERIAL ',
       'CLASIFICACIÓN ', 'U M', 'OBSERVACIONES'],
      dtype='object')

# Transformación

In [9]:
# Se eliminan espacios en blanco de los nombres de las columnas
insumos.columns = insumos.columns.str.strip()
insumos.columns

Index(['ITEM', 'CODIGO SAP/OTRO', 'DESCRIPCION DEL MATERIAL', 'CLASIFICACIÓN',
       'U M', 'OBSERVACIONES'],
      dtype='object')

### Categorias unicas de la clasificación.

In [10]:
insumos['CLASIFICACIÓN'].unique()

array(['PIPING ', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN ',
       'PIEZÓMETROS ', 'IMPERMEABILIAZACIÓN ', 'OBRAS CIVILES ',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA', 'TALLER BERLIAM',
       nan, 'RIEGO MURO TRANQUE', 'INSTRUMENTACIÓN GEOTECNICA'],
      dtype=object)

In [11]:
insumos['CLASIFICACIÓN'] = insumos['CLASIFICACIÓN'].str.strip()
insumos['CLASIFICACIÓN'].unique()

array(['PIPING', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN',
       'PIEZÓMETROS', 'IMPERMEABILIAZACIÓN', 'OBRAS CIVILES',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA', 'TALLER BERLIAM',
       nan, 'RIEGO MURO TRANQUE', 'INSTRUMENTACIÓN GEOTECNICA'],
      dtype=object)

### Verificación valores nulos

In [12]:
# Revisión de valores nulos en la columna CLASIFICACIÓN
insumos[insumos['CLASIFICACIÓN'].isnull()]
# TODO: llenar clasificación NaN

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
481,11.29,11220592,MAURO TUERCA STORZ 4 PULGADAS LINEA DE RIEGO,NaN,UN,NaN

In [13]:
insumos[insumos['CODIGO SAP/OTRO'].isnull()]
# TODO: Considerar iluminación empalizada como categoría?

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
490,NaN,NaN,NaN,ILUMINACION EMPALIZADA,NaN,NaN

In [14]:
insumos[insumos['U M'].isnull()]
# TODO: Llenar unidades de medida faltantes

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
166,4.40,catalogar sap,"Flange Ciego diam 28"" ANSI C150",PIEZAS ESPECIALES,NaN,NaN
167,4.50,catalogar sap,"Flange Ciego 28"" ANSI C300",PIEZAS ESPECIALES,NaN,NaN
348,9.95,catalogar sap,Tubos PVC Bastones Reflectantes,SERVICIOS GENERALES,NaN,NaN
352,9.99,11215216,BOQUILLAS DEPOSITACION 50MM POLIURETANO,SERVICIOS GENERALES,NaN,NaN
490,NaN,NaN,NaN,ILUMINACION EMPALIZADA,NaN,NaN

## Valores duplicados

In [15]:
insumos[insumos['CODIGO SAP/OTRO'].duplicated(keep=False)]

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
2,1.30,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN
5,1.60,11021056,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,NaN
57,1.59,en catalogacion,"DUCTO RECTO Ø8""X500MM EXT.FLG SO Ø10"" ANSI #15...",PIPING,UN,NaN
58,1.60,en catalogacion,"DUCTO RECTO Ø11""X500MM EXT.FLG SO Ø10"" ANSI #1...",PIPING,UN,NaN
59,1.61,en catalogacion,"DUCTO RECTO Ø11""X300MM EXT.FLG SO Ø10"" ANSI #1...",PIPING,UN,NaN
60,1.62,en catalogacion,"DUCTO RECTO Ø11""X1000MM EXT.FLG SO Ø10"" ANSI #...",PIPING,UN,NaN
61,1.63,en catalogacion,"DUCTO RECTO Ø10""X500MM EXT.FLG SO Ø10"" ANSI #1...",PIPING,UN,NaN
62,1.64,en catalogacion,"DUCTO RECTO Ø10""X300MM EXT.FLG SO Ø10"" ANSI #1...",PIPING,UN,NaN
63,1.65,en catalogacion,"DUCTO RECTO Ø10""X1000MM EXT.FLG SO Ø10"" ANSI #...",PIPING,UN,NaN
83,2.17,11021056,"DUCTO RECTO;10"" DIA X 500MM LG SLIP ON",PIEZAS ESPECIALES,UN,NaN
166,4.40,catalogar sap,"Flange Ciego diam 28"" ANSI C150",PIEZAS ESPECIALES,NaN,NaN
167,4.50,catalogar sap,"Flange Ciego 28"" ANSI C300",PIEZAS ESPECIALES,NaN,NaN
243,8.13,catalogar sap,"ESPARRAGO;3/4"" X 9""LG ACERO 4340",VALVULAS,UN,NaN
282,9.29,44001452,Supresor de Polvo\nAGENTE SUPRESOR;AGUASIN;TQ1...,HUMECTACIÓN,Bins,NaN
299,9.46,catalogar sap,Aporte Extrusion 4 MM,IMPERMEABILIAZACIÓN,kg,NaN
300,9.47,catalogar sap,Solera Anclaje HDPE,IMPERMEABILIAZACIÓN,Mt,NaN
314,9.61,catalogar sap,Wear Guard DEVCON,OBRAS CIVILES,lts,NaN
315,9.62,catalogar sap,Cemento Normal ( melon),OBRAS CIVILES,UN,NaN
316,9.63,catalogar sap,Hormigon Predosificado c03 h-20,OBRAS CIVILES,UN,NaN
334,9.81,11184744,Kit Mangueras depositación coronamiento rigida,SERVICIOS GENERALES,Unidad,NaN
335,9.82,44001452,Bines de supresor de polvo AGUASIN; TQ15808,SERVICIOS GENERALES,Bin,NaN
348,9.95,catalogar sap,Tubos PVC Bastones Reflectantes,SERVICIOS GENERALES,NaN,NaN
350,9.97,catalogar sap,Cintas reflectantes (Piezometros - Aspersores),SERVICIOS GENERALES,UN,NaN
356,10.40,en catalogacion,"TAPON CONICO;6-1/2"" X 7/8"" DIA MADERA, diam 76 mm",SERVICIOS GENERALES,UN,NaN
364,10.12,11184744,MANGUERAS DEPOSITACIÓN,SERVICIOS GENERALES,UN,NaN

In [16]:
codigos_duplicados = insumos[insumos['CODIGO SAP/OTRO'].duplicated(keep=False)]['CODIGO SAP/OTRO'].unique()

In [17]:
insumos[insumos['CODIGO SAP/OTRO'] == 'en catalogacion']['DESCRIPCION DEL MATERIAL']

2      Tuberia HDPE 200MM DN, Flanges Moviles C150, c...
57     DUCTO RECTO Ø8"X500MM EXT.FLG SO Ø10" ANSI #15...
58     DUCTO RECTO Ø11"X500MM EXT.FLG SO Ø10" ANSI #1...
59     DUCTO RECTO Ø11"X300MM EXT.FLG SO Ø10" ANSI #1...
60     DUCTO RECTO Ø11"X1000MM EXT.FLG SO Ø10" ANSI #...
61     DUCTO RECTO Ø10"X500MM EXT.FLG SO Ø10" ANSI #1...
62     DUCTO RECTO Ø10"X300MM EXT.FLG SO Ø10" ANSI #1...
63     DUCTO RECTO Ø10"X1000MM EXT.FLG SO Ø10" ANSI #...
356    TAPON CONICO;6-1/2" X 7/8" DIA MADERA, diam 76 mm
Name: DESCRIPCION DEL MATERIAL, dtype: object

In [18]:
insumos['U M'].unique()
# TODO: Corregir UM inconsistentes

array(['UN', nan, 'kit', 'Bins', 'M2', 'ROLLOS', 'M3', 'M', 'kg', 'Mt',
       'Kg', 'Metros', 'KIT', 'lts', 'mt', 'Unidad', 'Bin', 'Rollo',
       'saco 25 kg', 'Kit'], dtype=object)

In [19]:
insumos.head(3)

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
0,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN
1,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN
2,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN

In [20]:
insumos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ITEM                      490 non-null    float64
 1   CODIGO SAP/OTRO           490 non-null    object
 2   DESCRIPCION DEL MATERIAL  490 non-null    object
 3   CLASIFICACIÓN             490 non-null    object
 4   U M                       486 non-null    object
 5   OBSERVACIONES             0 non-null      float64
dtypes: float64(2), object(4)
memory usage: 23.1+ KB

In [21]:
# Se filtra la tabla obteniendo solo los valores unicos por codigo SAP
insumos_limpios = insumos.drop_duplicates(subset=['CODIGO SAP/OTRO'], keep=False)

In [22]:
insumos_limpios.head(3)

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
0,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN
1,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN
3,1.4,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ...",PIPING,UN,NaN

## Cambio nombres de columnas

In [23]:
insumos_limpios = insumos_limpios. rename(columns={'CODIGO SAP/OTRO': 'CODIGO SAP', 'U M': 'UM', 'CLASIFICACIÓN': 'CLASIFICACION'})

In [24]:
insumos_limpios.columns

Index(['ITEM', 'CODIGO SAP', 'DESCRIPCION DEL MATERIAL', 'CLASIFICACION', 'UM',
       'OBSERVACIONES'],
      dtype='object')

# Carga

In [25]:
import sys
sys.path.append('..')

from src.database import InventarioDatabase

# # # Instanciamos la clase
db = InventarioDatabase('../src/db/inventario_lp02.db')
db.close

## Inputación de datos

In [26]:
# isnertar el dataframe:
for index, row in insumos_limpios.iterrows():
    db.insert_insumo(
        codigo_sap=row['CODIGO SAP'],
        descripcion=row['DESCRIPCION DEL MATERIAL'],
        clasificacion=row['CLASIFICACION'],
        um=row['UM'],
        observaciones=row['OBSERVACIONES']
    )

Insumo con código SAP 11174821 insertado correctamente.
Insumo con código SAP 11177716 insertado correctamente.
Insumo con código SAP 11151921 insertado correctamente.
Insumo con código SAP 11019704 insertado correctamente.
Insumo con código SAP 11010236 insertado correctamente.
Insumo con código SAP 11009715 insertado correctamente.
Insumo con código SAP 11214480 insertado correctamente.
Insumo con código SAP 11214458 insertado correctamente.
Insumo con código SAP 11214215 insertado correctamente.
Insumo con código SAP 11214116 insertado correctamente.
Insumo con código SAP 11010503 insertado correctamente.
Insumo con código SAP 11010504 insertado correctamente.
Insumo con código SAP 11010505 insertado correctamente.
Insumo con código SAP 11010506 insertado correctamente.
Insumo con código SAP 11010507 insertado correctamente.
Insumo con código SAP 11188680 insertado correctamente.
Insumo con código SAP 11188679 insertado correctamente.
Insumo con código SAP 11188678 insertado correctamente.
Insumo con código SAP 11188677 insertado correctamente.
Insumo con código SAP 11188676 insertado correctamente.
Insumo con código SAP 11151922 insertado correctamente.
Insumo con código SAP 11182677 insertado correctamente.
Insumo con código SAP 11010715 insertado correctamente.
Insumo con código SAP 11188664 insertado correctamente.
Insumo con código SAP 11188663 insertado correctamente.
Insumo con código SAP 11010713 insertado correctamente.
Insumo con código SAP 11220106 insertado correctamente.
Insumo con código SAP 11217090 insertado correctamente.
Insumo con código SAP 11216847 insertado correctamente.
Insumo con código SAP 11215311 insertado correctamente.
Insumo con código SAP 11009709 insertado correctamente.
Insumo con código SAP 11009710 insertado correctamente.
Insumo con código SAP 11188685 insertado correctamente.
Insumo con código SAP 11214913 insertado correctamente.
Insumo con código SAP 11021475 insertado correctamente.
Insumo con código SAP 11084585 insertado correctamente.
Insumo con código SAP 11017599 insertado correctamente.
Insumo con código SAP 11216764 insertado correctamente.
Insumo con código SAP 11219398 insertado correctamente.
Insumo con código SAP 11212167 insertado correctamente.
Insumo con código SAP 11167363 insertado correctamente.
Insumo con código SAP 11214659 insertado correctamente.
Insumo con código SAP 11188697 insertado correctamente.
Insumo con código SAP 11188696 insertado correctamente.
Insumo con código SAP 11188695 insertado correctamente.
Insumo con código SAP 11188694 insertado correctamente.
Insumo con código SAP 11019705 insertado correctamente.
Insumo con código SAP 11019706 insertado correctamente.
Insumo con código SAP 12000972 insertado correctamente.
Insumo con código SAP 11011495 insertado correctamente.
Insumo con código SAP 11174494 insertado correctamente.
Insumo con código SAP 11174493 insertado correctamente.
Insumo con código SAP 11189653 insertado correctamente.
Insumo con código SAP 11189652 insertado correctamente.
Insumo con código SAP 11189651 insertado correctamente.
Insumo con código SAP 11189647 insertado correctamente.
Insumo con código SAP 11189646 insertado correctamente.
Insumo con código SAP 11189645 insertado correctamente.
Insumo con código SAP 11189644 insertado correctamente.
Insumo con código SAP 11188675 insertado correctamente.
Insumo con código SAP 11188674 insertado correctamente.
Insumo con código SAP 11216848 insertado correctamente.
Insumo con código SAP 11216460 insertado correctamente.
Insumo con código SAP 11216462 insertado correctamente.
Insumo con código SAP 11216344 insertado correctamente.
Insumo con código SAP 11216345 insertado correctamente.
Insumo con código SAP 11216830 insertado correctamente.
Insumo con código SAP 11216347 insertado correctamente.
Insumo con código SAP 11216349 insertado correctamente.
Insumo con código SAP 11212162 insertado correctamente.
Insumo con código SAP 11212171 insertado correctamente.
Insumo con código SAP 11212174 insertado correctamente.
Insumo con código SAP 11021639 insertado correctamente.
Insumo con código SAP 11021637 insertado correctamente.
Insumo con código SAP 11010463 insertado correctamente.
Insumo con código SAP 11014385 insertado correctamente.
Insumo con código SAP 11021151 insertado correctamente.
Insumo con código SAP 11214515 insertado correctamente.
Insumo con código SAP 11215312 insertado correctamente.
Insumo con código SAP 11010379 insertado correctamente.
Insumo con código SAP 11021150 insertado correctamente.
Insumo con código SAP 11021149 insertado correctamente.
Insumo con código SAP 11010237 insertado correctamente.
Insumo con código SAP 11018390 insertado correctamente.
Insumo con código SAP 11188692 insertado correctamente.
Insumo con código SAP 11189133 insertado correctamente.
Insumo con código SAP 11020650
 insertado correctamente.
Insumo con código SAP 11016010 insertado correctamente.
Insumo con código SAP 11010385 insertado correctamente.
Insumo con código SAP 11014110 insertado correctamente.
Insumo con código SAP 11188684 insertado correctamente.
Insumo con código SAP 11188683 insertado correctamente.
Insumo con código SAP 11188682 insertado correctamente.
Insumo con código SAP 11188681 insertado correctamente.
Insumo con código SAP 11214445 insertado correctamente.
Insumo con código SAP 11214446 insertado correctamente.
Insumo con código SAP 11214521 insertado correctamente.
Insumo con código SAP 11214520 insertado correctamente.
Insumo con código SAP 11214444 insertado correctamente.
Insumo con código SAP 11218044 insertado correctamente.
Insumo con código SAP 11212170 insertado correctamente.
Insumo con código SAP 11212165 insertado correctamente.
Insumo con código SAP 11219139 insertado correctamente.
Insumo con código SAP 11219140 insertado correctamente.
Insumo con código SAP 11219141 insertado correctamente.
Insumo con código SAP 11219142 insertado correctamente.
Insumo con código SAP 11219143 insertado correctamente.
Insumo con código SAP 11219144 insertado correctamente.
Insumo con código SAP 11219819 insertado correctamente.
Insumo con código SAP 11219820 insertado correctamente.
Insumo con código SAP 11219822 insertado correctamente.
Insumo con código SAP 11221696 insertado correctamente.
Insumo con código SAP 11221697 insertado correctamente.
Insumo con código SAP 11221698 insertado correctamente.
Insumo con código SAP 11221699 insertado correctamente.
Insumo con código SAP 11221700 insertado correctamente.
Insumo con código SAP 11221701 insertado correctamente.
Insumo con código SAP 11221703 insertado correctamente.
Insumo con código SAP 11222641 insertado correctamente.
Insumo con código SAP 11220096 insertado correctamente.
Insumo con código SAP 11220097 insertado correctamente.
Insumo con código SAP 11220099 insertado correctamente.
Insumo con código SAP 11220101 insertado correctamente.
Insumo con código SAP 11216885 insertado correctamente.
Insumo con código SAP 11217695 insertado correctamente.
Insumo con código SAP 11217711 insertado correctamente.
Insumo con código SAP 11221838 insertado correctamente.
Insumo con código SAP 11014109 insertado correctamente.
Insumo con código SAP 11014107 insertado correctamente.
Insumo con código SAP 11014108 insertado correctamente.
Insumo con código SAP 11014111 insertado correctamente.
Insumo con código SAP 11014076 insertado correctamente.
Insumo con código SAP 11189132 insertado correctamente.
Insumo con código SAP 11189131 insertado correctamente.
Insumo con código SAP 11189130 insertado correctamente.
Insumo con código SAP 11189129 insertado correctamente.
Insumo con código SAP 11189128 insertado correctamente.
Insumo con código SAP 11189127 insertado correctamente.
Insumo con código SAP 11189126 insertado correctamente.
Insumo con código SAP 11189125 insertado correctamente.
Insumo con código SAP 11213967 insertado correctamente.
Insumo con código SAP 11213969 insertado correctamente.
Insumo con código SAP 11213970 insertado correctamente.
Insumo con código SAP 11213972 insertado correctamente.
Insumo con código SAP 11213973 insertado correctamente.
Insumo con código SAP 11014178 insertado correctamente.
Insumo con código SAP 11014179 insertado correctamente.
Insumo con código SAP 11020143 insertado correctamente.
Insumo con código SAP 11020155 insertado correctamente.
Insumo con código SAP 11188691 insertado correctamente.
Insumo con código SAP 11188690 insertado correctamente.
Insumo con código SAP 11188689 insertado correctamente.
Insumo con código SAP 11189120 insertado correctamente.
Insumo con código SAP 11188688 insertado correctamente.
Insumo con código SAP 11188687 insertado correctamente.
Insumo con código SAP 11188686 insertado correctamente.
Insumo con código SAP 11215310 insertado correctamente.
Insumo con código SAP 11018117 insertado correctamente.
Insumo con código SAP 11023641 insertado correctamente.
Insumo con código SAP 11189117 insertado correctamente.
Insumo con código SAP 11189116 insertado correctamente.
Insumo con código SAP 11189124 insertado correctamente.
Insumo con código SAP 11189123 insertado correctamente.
Insumo con código SAP 11188668 insertado correctamente.
Insumo con código SAP 11188667 insertado correctamente.
Insumo con código SAP 11188666 insertado correctamente.
Insumo con código SAP 11188665 insertado correctamente.
Insumo con código SAP 11214516 insertado correctamente.
Insumo con código SAP 11217092 insertado correctamente.
Insumo con código SAP 11217089 insertado correctamente.
Insumo con código SAP 11218787 insertado correctamente.
Insumo con código SAP 11218782 insertado correctamente.
Insumo con código SAP 11218783 insertado correctamente.
Insumo con código SAP 11218784 insertado correctamente.
Insumo con código SAP 11220105 insertado correctamente.
Insumo con código SAP 11220104 insertado correctamente.
Insumo con código SAP 11220103 insertado correctamente.
Insumo con código SAP 11220102 insertado correctamente.
Insumo con código SAP 11220177 insertado correctamente.
Insumo con código SAP 11220176 insertado correctamente.
Insumo con código SAP 11220175 insertado correctamente.
Insumo con código SAP 11220174 insertado correctamente.
Insumo con código SAP 11220173 insertado correctamente.
Insumo con código SAP 11220172 insertado correctamente.
Insumo con código SAP 11010962 insertado correctamente.
Insumo con código SAP 11178700 insertado correctamente.
Insumo con código SAP 11178702 insertado correctamente.
Insumo con código SAP 11010277 insertado correctamente.
Insumo con código SAP 11211977 insertado correctamente.
Insumo con código SAP 11117559 insertado correctamente.
Insumo con código SAP 11087505 insertado correctamente.
Insumo con código SAP 11019229 insertado correctamente.
Insumo con código SAP 11019154 insertado correctamente.
Insumo con código SAP 88000142 insertado correctamente.
Insumo con código SAP 11015103 insertado correctamente.
Insumo con código SAP 11013752 insertado correctamente.
Insumo con código SAP 11010239 insertado correctamente.
Insumo con código SAP 11013747 insertado correctamente.
Insumo con código SAP 11017089 insertado correctamente.
Insumo con código SAP 88000081 insertado correctamente.
Insumo con código SAP 12000774 insertado correctamente.
Insumo con código SAP 12010335 insertado correctamente.
Insumo con código SAP 12010336 insertado correctamente.
Insumo con código SAP 11008954 insertado correctamente.
Insumo con código SAP 11010243 insertado correctamente.
Insumo con código SAP 11020115 insertado correctamente.
Insumo con código SAP 11013029 insertado correctamente.
Insumo con código SAP 11013030 insertado correctamente.
Insumo con código SAP 11084547 insertado correctamente.
Insumo con código SAP 12004083 insertado correctamente.
Insumo con código SAP 88000184 insertado correctamente.
Insumo con código SAP 11015895 insertado correctamente.
Insumo con código SAP 11020020 insertado correctamente.
Insumo con código SAP 11183480 insertado correctamente.
Insumo con código SAP 11183481 insertado correctamente.
Insumo con código SAP 11216762 insertado correctamente.
Insumo con código SAP 22003670 insertado correctamente.
Insumo con código SAP 22003671 insertado correctamente.
Insumo con código SAP 22002942 insertado correctamente.
Insumo con código SAP 11019133 insertado correctamente.
Insumo con código SAP 22003422 insertado correctamente.
Insumo con código SAP 11021401 insertado correctamente.
Insumo con código SAP 11021398 insertado correctamente.
Insumo con código SAP 11020376 insertado correctamente.
Insumo con código SAP 11021399 insertado correctamente.
Insumo con código SAP 11019722 insertado correctamente.
Insumo con código SAP 22002945 insertado correctamente.
Insumo con código SAP 22003216 insertado correctamente.
Insumo con código SAP 11090702 insertado correctamente.
Insumo con código SAP 22003316 insertado correctamente.
Insumo con código SAP 22003115 insertado correctamente.
Insumo con código SAP 22003362 insertado correctamente.
Insumo con código SAP 22002944 insertado correctamente.
Insumo con código SAP 22002769 insertado correctamente.
Insumo con código SAP 22003213 insertado correctamente.
Insumo con código SAP 22003042 insertado correctamente.
Insumo con código SAP 22003685 insertado correctamente.
Insumo con código SAP 22003317 insertado correctamente.
Insumo con código SAP 22003877 insertado correctamente.
Insumo con código SAP 11187366 insertado correctamente.
Insumo con código SAP 22003363 insertado correctamente.
Insumo con código SAP 22003318 insertado correctamente.
Insumo con código SAP 22003208 insertado correctamente.
Insumo con código SAP 11220181 insertado correctamente.
Insumo con código SAP 11220180 insertado correctamente.
Insumo con código SAP 11219877 insertado correctamente.
Insumo con código SAP 11220121 insertado correctamente.
Insumo con código SAP 22003058 insertado correctamente.
Insumo con código SAP 22002973 insertado correctamente.
Insumo con código SAP 22011463 insertado correctamente.
Insumo con código SAP 22002943 insertado correctamente.
Insumo con código SAP 22003212 insertado correctamente.
Insumo con código SAP 22003424 insertado correctamente.
Insumo con código SAP 22000311 insertado correctamente.
Insumo con código SAP 11216124 insertado correctamente.
Insumo con código SAP 11216642 insertado correctamente.
Insumo con código SAP 22002772 insertado correctamente.
Insumo con código SAP 22003768 insertado correctamente.
Insumo con código SAP 11021075 insertado correctamente.
Insumo con código SAP 22003464 insertado correctamente.
Insumo con código SAP 11017558 insertado correctamente.
Insumo con código SAP 11016400 insertado correctamente.
Insumo con código SAP 11010217 insertado correctamente.
Insumo con código SAP 11127227 insertado correctamente.
Insumo con código SAP 11019047 insertado correctamente.
Insumo con código SAP 11180037 insertado correctamente.
Insumo con código SAP 11188671 insertado correctamente.
Insumo con código SAP 11188670 insertado correctamente.
Insumo con código SAP 11188669 insertado correctamente.
Insumo con código SAP 11220570 insertado correctamente.
Insumo con código SAP 11215167 insertado correctamente.
Insumo con código SAP 11167118 insertado correctamente.
Insumo con código SAP 11012101 insertado correctamente.
Insumo con código SAP 11019976 insertado correctamente.
Insumo con código SAP 11012103 insertado correctamente.
Insumo con código SAP 11012180 insertado correctamente.
Insumo con código SAP 22003324 insertado correctamente.
Insumo con código SAP 11017598 insertado correctamente.
Insumo con código SAP 22015853 insertado correctamente.
Insumo con código SAP 11018319 insertado correctamente.
Insumo con código SAP 22015666 insertado correctamente.
Insumo con código SAP 11009707 insertado correctamente.
Insumo con código SAP 11019930 insertado correctamente.
Insumo con código SAP 11185704 insertado correctamente.
Insumo con código SAP 22015864 insertado correctamente.
Insumo con código SAP 22003330 insertado correctamente.
Insumo con código SAP 22003328 insertado correctamente.
Insumo con código SAP 11015725 insertado correctamente.
Insumo con código SAP 11015724 insertado correctamente.
Insumo con código SAP 11014419 insertado correctamente.
Insumo con código SAP 22007412 insertado correctamente.
Insumo con código SAP 22007414 insertado correctamente.
Insumo con código SAP 22007415 insertado correctamente.
Insumo con código SAP 22007416 insertado correctamente.
Insumo con código SAP 22003326 insertado correctamente.
Insumo con código SAP 22003997 insertado correctamente.
Insumo con código SAP 22010344 insertado correctamente.
Insumo con código SAP 22015472 insertado correctamente.
Insumo con código SAP 11189121 insertado correctamente.
Insumo con código SAP 22010346 insertado correctamente.
Insumo con código SAP 22010348 insertado correctamente.
Insumo con código SAP 22010345 insertado correctamente.
Insumo con código SAP 44002471 insertado correctamente.
Insumo con código SAP 22015855 insertado correctamente.
Insumo con código SAP 22003331 insertado correctamente.
Insumo con código SAP 11188495 insertado correctamente.
Insumo con código SAP 11188673 insertado correctamente.
Insumo con código SAP 11188672 insertado correctamente.
Insumo con código SAP 11214401 insertado correctamente.
Insumo con código SAP 11179000 insertado correctamente.
Insumo con código SAP 11215498 insertado correctamente.
Insumo con código SAP 11176304 insertado correctamente.
Insumo con código SAP 11186792 insertado correctamente.
Insumo con código SAP 12001131 insertado correctamente.
Insumo con código SAP 11176305 insertado correctamente.
Insumo con código SAP 44001533 insertado correctamente.
Insumo con código SAP 44002047 insertado correctamente.
Insumo con código SAP 22010349 insertado correctamente.
Insumo con código SAP 22003662 insertado correctamente.
Insumo con código SAP 22003658 insertado correctamente.
Insumo con código SAP 22003657 insertado correctamente.
Insumo con código SAP 22004051 insertado correctamente.
Insumo con código SAP 22004049 insertado correctamente.
Insumo con código SAP 22004050 insertado correctamente.
Insumo con código SAP 22004048 insertado correctamente.
Insumo con código SAP 22003329 insertado correctamente.
Insumo con código SAP 44000151 insertado correctamente.
Insumo con código SAP 22003591 insertado correctamente.
Insumo con código SAP 22007382 insertado correctamente.
Insumo con código SAP 11215216 insertado correctamente.
Insumo con código SAP 11021059 insertado correctamente.
Insumo con código SAP 11214644 insertado correctamente.
Insumo con código SAP 22003321 insertado correctamente.
Insumo con código SAP 11020112 insertado correctamente.
Insumo con código SAP 22004102 insertado correctamente.
Insumo con código SAP 22003428 insertado correctamente.
Insumo con código SAP 11171151 insertado correctamente.
Insumo con código SAP 11186859 insertado correctamente.
Insumo con código SAP 11186860 insertado correctamente.
Insumo con código SAP 11186861 insertado correctamente.
Insumo con código SAP 1190167 insertado correctamente.
Insumo con código SAP 11210704 insertado correctamente.
Insumo con código SAP 22003663 insertado correctamente.
Insumo con código SAP 11210298 insertado correctamente.
Insumo con código SAP 11210302 insertado correctamente.
Insumo con código SAP 22002438 insertado correctamente.
Insumo con código SAP 20-000020 insertado correctamente.
Insumo con código SAP 50-000050 insertado correctamente.
Insumo con código SAP 80-000080 insertado correctamente.
Insumo con código SAP 110-0000110 insertado correctamente.
Insumo con código SAP 10-000010 insertado correctamente.
Insumo con código SAP 40-000040 insertado correctamente.
Insumo con código SAP 60-000060 insertado correctamente.
Insumo con código SAP 70-000070 insertado correctamente.
Insumo con código SAP 90-000090 insertado correctamente.
Insumo con código SAP 100-0000100 insertado correctamente.

## Prueba de creación tabla

In [ ]:
import sqlite3
conexion = sqlite3.connect('../src/db/inventario_lp02.db')
# cursor = conexion.cursor()
# cursor.execute("SELECT * FROM insumos")
# consulta = cursor.fetchall()
tablas = pd.read_sql_query("SELECT * FROM sqlite_master", conexion)
conexion.close()
tablas

,type,name,tbl_name,rootpage,sql
0,table,insumos,insumos,2,"CREATE TABLE insumos (\n ""CODIG..."
1,index,sqlite_autoindex_insumos_1,insumos,3,None

In [48]:
conexion = sqlite3.connect('../src/db/inventario_lp02.db')
tabla_insumos = pd.read_sql_query("SELECT * FROM insumos", conexion)
conexion.close()
tabla_insumos.head()

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,OBSERVACIONES
0,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,None
1,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,None
2,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ...",PIPING,UN,None
3,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,None
4,11010236,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,None