# Importación de librerías

In [1]:
import pandas as pd
import sqlite3

# Ingesta de datos

In [2]:
salidas = pd.read_excel("..\data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='SALIDA', skiprows=9)

In [3]:
salidas.head()

,Unnamed: 0,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO,Unnamed: 12
0,NaN,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,6.0,2025-09-30 00:00:00,NaN,OPERACIONES,RENE MENDOZA,EMPALIZADA,COSAPI,NaN
1,NaN,VALVULAS,22002942,"ESPARRAGO;7/8"" X 1MT LG GRADO 5",UN,12.0,2025-10-09 00:00:00,NaN,OPERACIONES,NELSON AGUILERA,TALLER SOLDADOR,BODEGA RELIX,NaN
2,NaN,VALVULAS,22003670,"ESPARRAGO;7/8"" X 8"" LG GRADO 5",UN,64.0,2025-10-09 00:00:00,NaN,OPERACIONES,ANIBAL ESCOBAR,EMPALIZADA,BODEGA RELIX,NaN
3,NaN,PIPING,11188685,"EMPAQ. FF DN- 10"" # 300 EN BA-U 1/8"" S/ANSI B ...",UN,6.0,2025-10-09 00:00:00,NaN,OPERACIONES,HUGO SALAZAR,EMPALIZADA,BODEGA RELIX,NaN
4,NaN,PIPING,11009709,"EMPAQUETADURA;8"" ANSI 150 8 PERF",UN,10.0,2025-10-10 00:00:00,NaN,OPERACIONES,ERNESTO DIAZ,LINEA PEUMO L3,BODEGA RELIX,NaN

# Transformación

## Columnas

In [4]:
salidas = salidas.drop(salidas.columns[[0, 12]], axis=1)
salidas.head()

,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO
0,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,6.0,2025-09-30 00:00:00,NaN,OPERACIONES,RENE MENDOZA,EMPALIZADA,COSAPI
1,VALVULAS,22002942,"ESPARRAGO;7/8"" X 1MT LG GRADO 5",UN,12.0,2025-10-09 00:00:00,NaN,OPERACIONES,NELSON AGUILERA,TALLER SOLDADOR,BODEGA RELIX
2,VALVULAS,22003670,"ESPARRAGO;7/8"" X 8"" LG GRADO 5",UN,64.0,2025-10-09 00:00:00,NaN,OPERACIONES,ANIBAL ESCOBAR,EMPALIZADA,BODEGA RELIX
3,PIPING,11188685,"EMPAQ. FF DN- 10"" # 300 EN BA-U 1/8"" S/ANSI B ...",UN,6.0,2025-10-09 00:00:00,NaN,OPERACIONES,HUGO SALAZAR,EMPALIZADA,BODEGA RELIX
4,PIPING,11009709,"EMPAQUETADURA;8"" ANSI 150 8 PERF",UN,10.0,2025-10-10 00:00:00,NaN,OPERACIONES,ERNESTO DIAZ,LINEA PEUMO L3,BODEGA RELIX

In [5]:
salidas.columns = salidas.columns.str.strip()
salidas.columns

Index(['CLASIFICIACIÓN', 'CÓDIGO         SAP / OTRO',
       'DESCRIPCIÓN DEL MATERIAL', 'UNIDAD', 'CANTIDAD', 'FECHA DE SALIDA',
       'N° DE GUÍA DE SALIDAD', 'USO:  OPERACIONES / PROYECTO',
       'ENTREGADO  A:', 'COMENTARIOS', 'UBICACIÓN DE RETIRO'],
      dtype='object')

In [6]:
salidas = salidas.rename(columns={'CÓDIGO         SAP / OTRO': 'CODIGO SAP', 
                                    'CLASIFICIACIÓN': 'CLASIFICACION', 
                                    'DESCRIPCIÓN DEL MATERIAL': 'DESCRIPCION DEL MATERIAL', 
                                    'UNIDAD': 'UM',
                                    'UBICACIÓN': 'UBICACION',
                                    'ENTREGADO A:': 'ENTREGADO A',
                                    'USO:  OPERACIONES / PROYECTO': 'USO: OPERACIONES/PROYECTO',
                                    'UBICACIÓN DE RETIRO': 'UBICACION DE RETIRO',
                                    'N° DE GUÍA DE SALIDAD': 'N° DE GUIA DE SALIDA',
                                    })
salidas.columns

Index(['CLASIFICACION', 'CODIGO SAP', 'DESCRIPCION DEL MATERIAL', 'UM',
       'CANTIDAD', 'FECHA DE SALIDA', 'N° DE GUIA DE SALIDA',
       'USO: OPERACIONES/PROYECTO', 'ENTREGADO  A:', 'COMENTARIOS',
       'UBICACION DE RETIRO'],
      dtype='object')

## Categorías únicas por columna

In [7]:
salidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CLASIFICACION              341 non-null    object
 1   CODIGO SAP                 341 non-null    object
 2   DESCRIPCION DEL MATERIAL   341 non-null    object
 3   UM                         341 non-null    object
 4   CANTIDAD                   341 non-null    float64
 5   FECHA DE SALIDA            341 non-null    object
 6   N° DE GUIA DE SALIDA       0 non-null      float64
 7   USO: OPERACIONES/PROYECTO  341 non-null    object
 8   ENTREGADO  A:              341 non-null    object
 9   COMENTARIOS                339 non-null    object
 10  UBICACION DE RETIRO        275 non-null    object
dtypes: float64(2), object(9)
memory usage: 48.2+ KB

In [8]:
salidas['CLASIFICACION'].unique()

array(['VALVULAS', 'PIPING ', 'HUMECTACIÓN ', 'SERVICIOS GENERALES',
       'PIEZA ESPECIAL', 'IMPERMEABILIAZACIÓN ', 'PIEZÓMETROS ',
       'PIEZAS ESPECIALES', 'OBRAS CIVILES ', nan], dtype=object)

In [9]:
salidas = salidas.dropna(subset=['CODIGO SAP'])

In [10]:
salidas['CANTIDAD'] = salidas['CANTIDAD'].astype(int)

In [11]:
salidas['CLASIFICACION'].unique()

array(['VALVULAS', 'PIPING ', 'HUMECTACIÓN ', 'SERVICIOS GENERALES',
       'PIEZA ESPECIAL', 'IMPERMEABILIAZACIÓN ', 'PIEZÓMETROS ',
       'PIEZAS ESPECIALES', 'OBRAS CIVILES '], dtype=object)

In [12]:
salidas['UM'].unique()

array(['UN', 'Unidad', 'kg', 'M2', 'Kit', 'M3'], dtype=object)

In [13]:
# Estandarización de categorías y unidades de medida
import sys
sys.path.append('..')
from src.data_process import estandarizar_datos

salidas, valores_unicos_clasificacion, valores_unicos_um = estandarizar_datos(salidas)

✅ Unidades estandarizadas
✅ Clasificación estandarizada

In [14]:
valores_unicos_clasificacion

array(['VALVULAS', 'PIPING', 'HUMECTACION', 'SERVICIOS GENERALES',
       'PIEZAS ESPECIALES', 'IMPERMEABILIZACION', 'PIEZOMETROS',
       'OBRAS CIVILES'], dtype=object)

In [15]:
valores_unicos_um

array(['UNIDAD', 'KG', 'M2', 'KIT', 'M3'], dtype=object)

### Verificación valores nulos

In [16]:
salidas[salidas['CODIGO SAP'].isnull()]

Empty DataFrame
Columns: [CLASIFICACION, CODIGO SAP, DESCRIPCION DEL MATERIAL, UM, CANTIDAD, FECHA DE SALIDA, N° DE GUIA DE SALIDA, USO: OPERACIONES/PROYECTO, ENTREGADO  A:, COMENTARIOS, UBICACION DE RETIRO]
Index: []

In [17]:
salidas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 341 entries, 0 to 340
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CLASIFICACION              341 non-null    object
 1   CODIGO SAP                 341 non-null    object
 2   DESCRIPCION DEL MATERIAL   341 non-null    object
 3   UM                         341 non-null    object
 4   CANTIDAD                   341 non-null    int64
 5   FECHA DE SALIDA            341 non-null    object
 6   N° DE GUIA DE SALIDA       0 non-null      float64
 7   USO: OPERACIONES/PROYECTO  341 non-null    object
 8   ENTREGADO  A:              341 non-null    object
 9   COMENTARIOS                339 non-null    object
 10  UBICACION DE RETIRO        275 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 32.0+ KB

# Carga

In [18]:
import sys
import sqlite3
sys.path.append('..')

from src.database import InventarioDatabase

# instanciamos la base de datos
db = InventarioDatabase('../src/db/inventario_lp02.db')
# Creamos la tabla insumos en la base de datos
conexion = sqlite3.connect('../src/db/inventario_lp02.db')
cursor = conexion.cursor()
cursor.execute('''
        CREATE TABLE IF NOT EXISTS salidas (
            "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
            "CODIGO SAP" TEXT NOT NULL,
            "CLASIFICACION" TEXT NOT NULL,
            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,
            "UM" TEXT NOT NULL,
            "CANTIDAD" INTEGER NOT NULL,
            "FECHA DE SALIDA" DATE NOT NULL,
            "N° DE GUIA DE SALIDA" TEXT,
            "USO: OPERACIONES/PROYECTO" TEXT,
            "ENTREGADO A" TEXT,
            "COMENTARIOS" TEXT,
            "UBICACION DE RETIRO" TEXT,
            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")
        )
    ''')
consulta = cursor.fetchall()
conexion.close()

In [19]:
for index, row in salidas.iterrows():
    db.insert_salida(
        codigo_sap=row['CODIGO SAP'],
        clasificacion=row['CLASIFICACION'],
        descripcion=row['DESCRIPCION DEL MATERIAL'],
        um=row['UM'],
        cantidad=row['CANTIDAD'],
        fecha_salida=row['FECHA DE SALIDA'],
        guia_salida=row.get('N° DE GUIA DE SALIDA'),
        uso=row.get('USO: OPERACIONES/PROYECTO'),
        entregado_a=row.get('ENTREGADO A'),
        comentarios=row.get('COMENTARIOS'),
        ubicacion=row.get('UBICACION DE RETIRO')
    )
db.close()

✓ salida con código SAP 11117559 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11010715 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 11180037 insertado correctamente.
✓ salida con código SAP 11019047 insertado correctamente.
✓ salida con código SAP 22003591 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11220181 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11021639 insertado correctamente.
✓ salida con código SAP 11174821 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 11220181 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11176304 insertado correctamente.
✓ salida con código SAP 11220181 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP catalogar sap insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 1111112 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22015666 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 11019047 insertado correctamente.
✓ salida con código SAP 11214215 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11117559 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11019047 insertado correctamente.
✓ salida con código SAP 11188670 insertado correctamente.
✓ salida con código SAP 11180037 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 11220181 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 1111113 insertado correctamente.
✓ salida con código SAP 11019930 insertado correctamente.
✓ salida con código SAP 11219877 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11010715 insertado correctamente.
✓ salida con código SAP 11215167 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 11180037 insertado correctamente.
✓ salida con código SAP AA156414 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11117559 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11214215 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 11214445 insertado correctamente.
✓ salida con código SAP 11010715 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 11214215 insertado correctamente.
✓ salida con código SAP 11214215 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11214215 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 22015472 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 11221697 insertado correctamente.
✓ salida con código SAP 11221696 insertado correctamente.
✓ salida con código SAP 11221701 insertado correctamente.
✓ salida con código SAP 11221700 insertado correctamente.
✓ salida con código SAP 11221698 insertado correctamente.
✓ salida con código SAP 11221699 insertado correctamente.
✓ salida con código SAP 11221703 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11216764 insertado correctamente.
✓ salida con código SAP 22002943 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 22003591 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11219142 insertado correctamente.
✓ salida con código SAP AA156414 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 22015666 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 22003321 insertado correctamente.
✓ salida con código SAP 11021059 insertado correctamente.
✓ salida con código SAP 11167118 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP SPY4153 insertado correctamente.
✓ salida con código SAP 11219877 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 11167118 insertado correctamente.
✓ salida con código SAP 11219139 insertado correctamente.
✓ salida con código SAP 11019930 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11219143 insertado correctamente.
✓ salida con código SAP 11167118 insertado correctamente.
✓ salida con código SAP 11210302 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11019930 insertado correctamente.
✓ salida con código SAP 11180037 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 11210298 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003321 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 22003997 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11219139 insertado correctamente.
✓ salida con código SAP 11221697 insertado correctamente.
✓ salida con código SAP 11221696 insertado correctamente.
✓ salida con código SAP 11221699 insertado correctamente.
✓ salida con código SAP 11221700 insertado correctamente.
✓ salida con código SAP 11221703 insertado correctamente.
✓ salida con código SAP 11221701 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 1111111 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22002942 insertado correctamente.
✓ salida con código SAP 22015666 insertado correctamente.
✓ salida con código SAP 11019930 insertado correctamente.
✓ salida con código SAP 22003591 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 11210704 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11216764 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11019930 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 1111113 insertado correctamente.
✓ salida con código SAP 1111111 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11219546 insertado correctamente.
✓ salida con código SAP 11167118 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 11019047 insertado correctamente.
✓ salida con código SAP 11219139 insertado correctamente.
✓ salida con código SAP 11219143 insertado correctamente.
✓ salida con código SAP 11019047 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11216642 insertado correctamente.
✓ salida con código SAP 11019930 insertado correctamente.
✓ salida con código SAP 22003670 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003208 insertado correctamente.
✓ salida con código SAP 11087505 insertado correctamente.
✓ salida con código SAP 11214480 insertado correctamente.
✓ salida con código SAP 11214215 insertado correctamente.
✓ salida con código SAP 11117559 insertado correctamente.
✓ salida con código SAP 11219139 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 22003213 insertado correctamente.
✓ salida con código SAP 1111113 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11009709 insertado correctamente.
✓ salida con código SAP 11009710 insertado correctamente.
✓ salida con código SAP 11188685 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11221700 insertado correctamente.
✓ salida con código SAP 11221698 insertado correctamente.
✓ salida con código SAP 11220121 insertado correctamente.
✓ salida con código SAP 22003362 insertado correctamente.
✓ salida con código SAP 11219139 insertado correctamente.
✓ salida con código SAP 22002945 insertado correctamente.
✓ salida con código SAP 11219139 insertado correctamente.
✓ salida con código SAP 22003329 insertado correctamente.

In [20]:
# import sqlite3
conexion = sqlite3.connect('../src/db/inventario_lp02.db')
cursor = conexion.cursor()
cursor.execute("SELECT * FROM sqlite_master")
consulta = cursor.fetchall()
# tablas = pd.read_sql_query("DROP TABLE insumos", conexion)
conexion.close()
consulta

[('table',
  'sqlite_sequence',
  'sqlite_sequence',
  18,
  'CREATE TABLE sqlite_sequence(name,seq)'),
 ('table',
  'insumos',
  'insumos',
  2,
  'CREATE TABLE insumos (\n            "CODIGO SAP" TEXT PRIMARY KEY,\n            "DESCRIPCION DEL MATERIAL" TEXT,\n            "CLASIFICACION" TEXT,\n            "UM" TEXT,\n            "OBSERVACIONES" TEXT\n        )'),
 ('index', 'sqlite_autoindex_insumos_1', 'insumos', 3, None),
 ('table',
  'ingresos',
  'ingresos',
  7,
  'CREATE TABLE ingresos (\n            "ID" INTEGER PRIMARY KEY AUTOINCREMENT,\n            "CODIGO SAP" TEXT NOT NULL,\n            "CLASIFICACION" TEXT NOT NULL,\n            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,\n            "UM" TEXT NOT NULL,\n            "CANTIDAD" INTEGER NOT NULL,\n            "FECHA DE INGRESO" DATE NOT NULL,\n            "RESERVA" TEXT,\n            "GUIA DESPACHO" TEXT,\n            "OC" TEXT,\n            "USO: OPERACIONES/PROYECTO" TEXT,\n            "RECIBIDO POR" TEXT,\n            "UBICACION" TEXT,\n            "EMPRESA" TEXT,\n            "PRECIO UNITARIO" REAL,\n            "OBSERVACIONES" TEXT,\n            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")\n        )'),
 ('table',
  'salidas',
  'salidas',
  9,
  'CREATE TABLE salidas (\n            "ID" INTEGER PRIMARY KEY AUTOINCREMENT,\n            "CODIGO SAP" TEXT NOT NULL,\n            "CLASIFICACION" TEXT NOT NULL,\n            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,\n            "UM" TEXT NOT NULL,\n            "CANTIDAD" INTEGER NOT NULL,\n            "FECHA DE SALIDA" DATE NOT NULL,\n            "N° DE GUIA DE SALIDA" TEXT,\n            "USO: OPERACIONES/PROYECTO" TEXT,\n            "ENTREGADO A" TEXT,\n            "COMENTARIOS" TEXT,\n            "UBICACION DE RETIRO" TEXT,\n            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")\n        )')]