# importación de librerías

In [41]:
import pandas as pd
import sqlite3

# Ingesta de datos

In [42]:
archivo_excel = pd.ExcelFile("..\data\INSUMOS OPERACIONALES STOCK RELIX.xlsx")
print("Hojas disponibles:", archivo_excel.sheet_names)

Hojas disponibles: ['Insumos Operacionales 2025', 'INGRESO', 'SALIDA', 'STOCK ']

In [43]:
stock = pd.read_excel("..\data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='STOCK ', skiprows=10)
stock.head()

,Unnamed: 0,ITEM,CODIGO SAP/OTRO,DESCRIPCION INSUMO,CLASIFICACIÓN,UNIDAD,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,Unidades,330.0,151.0,4.0,477.0,50.0,NaN,NaN,NaN
1,NaN,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,Unidades,406.0,0.0,0.0,406.0,50.0,NaN,NaN,NaN
2,NaN,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, con perforaciones diam 76mm",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0,NaN,NaN,NaN
3,NaN,1.4,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ( CARRETE DN 500 PN10 CLASE 150)",PIPING,Unidades,26.0,0.0,0.0,26.0,50.0,"19 Cosapi , 7 patio 2",NaN,NaN
4,NaN,1.5,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0,NaN,NaN,NaN

# Transformación

## Columnas

In [44]:
stock = stock.drop(stock.columns[[0, 1, 11, 12, 13]], axis=1)

In [45]:
stock.head()

,CODIGO SAP/OTRO,DESCRIPCION INSUMO,CLASIFICACIÓN,UNIDAD,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
0,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,Unidades,330.0,151.0,4.0,477.0,50.0
1,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,Unidades,406.0,0.0,0.0,406.0,50.0
2,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, con perforaciones diam 76mm",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0
3,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ( CARRETE DN 500 PN10 CLASE 150)",PIPING,Unidades,26.0,0.0,0.0,26.0,50.0
4,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0

In [46]:
stock.columns

Index(['CODIGO SAP/OTRO', 'DESCRIPCION INSUMO', 'CLASIFICACIÓN ', 'UNIDAD',
       'STOCK INICIAL', 'INGRESOS', 'SALIDAS', 'STOCK ACTUAL',
       'PUNTO DE REORDENAMIENTO'],
      dtype='object')

In [47]:
stock.columns = stock.columns.str.strip()
stock.columns

Index(['CODIGO SAP/OTRO', 'DESCRIPCION INSUMO', 'CLASIFICACIÓN', 'UNIDAD',
       'STOCK INICIAL', 'INGRESOS', 'SALIDAS', 'STOCK ACTUAL',
       'PUNTO DE REORDENAMIENTO'],
      dtype='object')

In [48]:
# Estandarización de nombre de columnas y eliminación de espacios
stock = stock.rename(columns={'CODIGO SAP/OTRO': 'CODIGO SAP', 
                                    'CLASIFICACIÓN': 'CLASIFICACION', 
                                    'DESCRIPCION INSUMO': 'DESCRIPCION DEL MATERIAL', 
                                    'UNIDAD': 'UM'
                                    })
stock.columns

Index(['CODIGO SAP', 'DESCRIPCION DEL MATERIAL', 'CLASIFICACION', 'UM',
       'STOCK INICIAL', 'INGRESOS', 'SALIDAS', 'STOCK ACTUAL',
       'PUNTO DE REORDENAMIENTO'],
      dtype='object')

## Categorias únicas por columna

In [49]:
stock['CLASIFICACION'].unique()

array(['PIPING ', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN ',
       'PIEZÓMETROS ', 'IMPERMEABILIAZACIÓN ', 'OBRAS CIVILES ',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA',
       'IMPERMEABILIZACIÓN LLAU-LLAU', 'TALLER BERLIAM', nan,
       'RIEGO MURO TRANQUE', 'INSTRUMENTACIÓN GEOTECNICA'], dtype=object)

In [50]:
stock[stock['CLASIFICACION'].isnull()]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
481,11220592,MAURO TUERCA STORZ 4 PULGADAS LINEA DE RIEGO,NaN,unidades,0.0,50.0,0.0,50.0,0.0

In [51]:
stock.loc[stock['CLASIFICACION'].isnull(), 'CLASIFICACION'] = 'PIEZAS ESPECIALIES'

In [52]:
stock['CLASIFICACION'] = stock['CLASIFICACION'].str.strip()

In [53]:
stock['CLASIFICACION'].unique()

array(['PIPING', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN',
       'PIEZÓMETROS', 'IMPERMEABILIAZACIÓN', 'OBRAS CIVILES',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA',
       'IMPERMEABILIZACIÓN LLAU-LLAU', 'TALLER BERLIAM',
       'PIEZAS ESPECIALIES', 'RIEGO MURO TRANQUE',
       'INSTRUMENTACIÓN GEOTECNICA'], dtype=object)

In [54]:
stock[stock['CODIGO SAP'].isnull()]

Empty DataFrame
Columns: [CODIGO SAP, DESCRIPCION DEL MATERIAL, CLASIFICACION, UM, STOCK INICIAL, INGRESOS, SALIDAS, STOCK ACTUAL, PUNTO DE REORDENAMIENTO]
Index: []

In [55]:
stock[stock['CODIGO SAP'].duplicated()]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
57,en catalogacion,"DUCTO RECTO Ø8""X500MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.10MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
58,en catalogacion,"DUCTO RECTO Ø11""X500MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.12MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
59,en catalogacion,"DUCTO RECTO Ø11""X300MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.12MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
60,en catalogacion,"DUCTO RECTO Ø11""X1000MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.12MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
61,en catalogacion,"DUCTO RECTO Ø10""X500MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.12MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
62,en catalogacion,"DUCTO RECTO Ø10""X300MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.12MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
63,en catalogacion,"DUCTO RECTO Ø10""X1000MM EXT.FLG SO Ø10"" ANSI #150/#300 REV.C.NAT.ESP.12MM 45±5 SH A",PIPING,Unidades,NaN,0.0,0.0,0.0,20.0
83,11021056,"DUCTO RECTO;10"" DIA X 500MM LG SLIP ON",PIEZAS ESPECIALES,Unidades,NaN,0.0,0.0,0.0,10.0
167,catalogar sap,"Flange Ciego 28"" ANSI C300",PIEZAS ESPECIALES,NaN,NaN,0.0,10.0,-10.0,2.0
243,catalogar sap,"ESPARRAGO;3/4"" X 9""LG ACERO 4340",VALVULAS,Unidades,NaN,0.0,0.0,0.0,1500.0
299,catalogar sap,Aporte Extrusion 4 MM,IMPERMEABILIAZACIÓN,kg,190.0,0.0,10.0,180.0,100.0
300,catalogar sap,Solera Anclaje HDPE,IMPERMEABILIAZACIÓN,Mt,NaN,0.0,NaN,0.0,50.0
314,catalogar sap,Wear Guard DEVCON,OBRAS CIVILES,lts,NaN,0.0,0.0,0.0,10.0
315,catalogar sap,Cemento Normal ( melon),OBRAS CIVILES,Unidades,NaN,0.0,0.0,0.0,20.0
316,catalogar sap,Hormigon Predosificado c03 h-20,OBRAS CIVILES,Unidades,NaN,0.0,0.0,0.0,30.0
335,44001452,Bines de supresor de polvo AGUASIN; TQ15808,SERVICIOS GENERALES,Bin,NaN,0.0,0.0,0.0,NaN
348,catalogar sap,Tubos PVC Bastones Reflectantes,SERVICIOS GENERALES,Unidades,NaN,0.0,NaN,0.0,50.0
350,catalogar sap,Cintas reflectantes (Piezometros - Aspersores),SERVICIOS GENERALES,unidades,NaN,0.0,NaN,0.0,NaN
356,en catalogacion,"TAPON CONICO;6-1/2"" X 7/8"" DIA MADERA, diam 76 mm",SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,100.0
364,11184744,MANGUERAS DEPOSITACIÓN,SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,30.0
482,10-00010,"CONECTOR TWIST LOCK , IP68, # 12 AWG 220V/16A 2P+T ( conector para luminaria IP68)",ILUMINACION EMPALIZADA,unidades,0.0,400.0,0.0,400.0,0.0

In [57]:
# Se estandarizan los códigos SAP pendientes pero quedan por catalogar
# Generar códigos únicos para evitar duplicados en PRIMARY KEY
contador = 1
mask = stock['CODIGO SAP'].isin(['en catalogacion', 'catalogar sap'])
for idx in stock[mask].index:
    stock.loc[idx, 'CODIGO SAP'] = f'POR_CATALOGAR_{contador:03d}'
    contador += 1

stock['DESCRIPCION DEL MATERIAL'] = stock['DESCRIPCION DEL MATERIAL'].str.strip()

In [58]:
stock[stock['CODIGO SAP'].duplicated()]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
83,11021056,"DUCTO RECTO;10"" DIA X 500MM LG SLIP ON",PIEZAS ESPECIALES,Unidades,NaN,0.0,0.0,0.0,10.0
335,44001452,Bines de supresor de polvo AGUASIN; TQ15808,SERVICIOS GENERALES,Bin,NaN,0.0,0.0,0.0,NaN
364,11184744,MANGUERAS DEPOSITACIÓN,SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,30.0
482,10-00010,"CONECTOR TWIST LOCK , IP68, # 12 AWG 220V/16A 2P+T ( conector para luminaria IP68)",ILUMINACION EMPALIZADA,unidades,0.0,400.0,0.0,400.0,0.0

### POR CONSIDERAR!!!

In [59]:
pd.set_option('display.width', None)         # Sin límite de ancho total
pd.set_option('display.max_colwidth', None)  # Sin límite de caracteres por columna

# LAS SIGUIENTES LÍNEAS SON PARA INVESTIGAR CÓDIGOS SAP DUPLICADOS
stock[stock['CODIGO SAP'] == '10-00010']

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
375,10-00010,"ARANDELA DE REPARTICION DIAM 1/2"", 40X40X4 , AC GALVANIZADO",ILUMINACION EMPALIZADA,unidades,0.0,400.0,0.0,400.0,0.0
482,10-00010,"CONECTOR TWIST LOCK , IP68, # 12 AWG 220V/16A 2P+T ( conector para luminaria IP68)",ILUMINACION EMPALIZADA,unidades,0.0,400.0,0.0,400.0,0.0

In [60]:
stock[stock['CODIGO SAP'] == 44001452]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
282,44001452,Supresor de Polvo\nAGENTE SUPRESOR;AGUASIN;TQ15808,HUMECTACIÓN,Bins,NaN,0.0,0.0,0.0,15.0
335,44001452,Bines de supresor de polvo AGUASIN; TQ15808,SERVICIOS GENERALES,Bin,NaN,0.0,0.0,0.0,NaN

In [61]:
stock[stock['CODIGO SAP'] == 11021056]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
5,11021056,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0
83,11021056,"DUCTO RECTO;10"" DIA X 500MM LG SLIP ON",PIEZAS ESPECIALES,Unidades,NaN,0.0,0.0,0.0,10.0

### Verificación valores nulos

In [62]:
stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CODIGO SAP                490 non-null    object
 1   DESCRIPCION DEL MATERIAL  490 non-null    object
 2   CLASIFICACION             490 non-null    object
 3   UM                        486 non-null    object
 4   STOCK INICIAL             185 non-null    float64
 5   INGRESOS                  489 non-null    float64
 6   SALIDAS                   486 non-null    float64
 7   STOCK ACTUAL              489 non-null    float64
 8   PUNTO DE REORDENAMIENTO   481 non-null    float64
dtypes: float64(5), object(4)
memory usage: 34.6+ KB

In [63]:
stock['CLASIFICACION'].unique()

array(['PIPING', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN',
       'PIEZÓMETROS', 'IMPERMEABILIAZACIÓN', 'OBRAS CIVILES',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA',
       'IMPERMEABILIZACIÓN LLAU-LLAU', 'TALLER BERLIAM',
       'PIEZAS ESPECIALIES', 'RIEGO MURO TRANQUE',
       'INSTRUMENTACIÓN GEOTECNICA'], dtype=object)

In [64]:
stock[stock['DESCRIPCION DEL MATERIAL'].isnull()]

Empty DataFrame
Columns: [CODIGO SAP, DESCRIPCION DEL MATERIAL, CLASIFICACION, UM, STOCK INICIAL, INGRESOS, SALIDAS, STOCK ACTUAL, PUNTO DE REORDENAMIENTO]
Index: []

In [65]:
stock[stock['CODIGO SAP'].isnull()]

Empty DataFrame
Columns: [CODIGO SAP, DESCRIPCION DEL MATERIAL, CLASIFICACION, UM, STOCK INICIAL, INGRESOS, SALIDAS, STOCK ACTUAL, PUNTO DE REORDENAMIENTO]
Index: []

In [66]:
stock[stock['UM'].isnull()]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
166,POR_CATALOGAR_009,"Flange Ciego diam 28"" ANSI C150",PIEZAS ESPECIALES,NaN,NaN,0.0,10.0,-10.0,2.0
167,POR_CATALOGAR_010,"Flange Ciego 28"" ANSI C300",PIEZAS ESPECIALES,NaN,NaN,0.0,10.0,-10.0,2.0
321,44002471,"POLYSEAL POLIMERO;1,05G/C3;TINETA",OBRAS CIVILES,NaN,NaN,0.0,0.0,0.0,30.0
352,11215216,BOQUILLAS DEPOSITACION 50MM POLIURETANO,SERVICIOS GENERALES,NaN,NaN,0.0,0.0,0.0,50.0

In [67]:
stock.loc[stock['UM'].isnull(), 'UM'] = 'UNIDAD'

In [68]:
stock[stock['UM'].isnull()]

Empty DataFrame
Columns: [CODIGO SAP, DESCRIPCION DEL MATERIAL, CLASIFICACION, UM, STOCK INICIAL, INGRESOS, SALIDAS, STOCK ACTUAL, PUNTO DE REORDENAMIENTO]
Index: []

In [69]:
stock[stock['STOCK INICIAL'].isnull()]

,CODIGO SAP,DESCRIPCION DEL MATERIAL,CLASIFICACION,UM,STOCK INICIAL,INGRESOS,SALIDAS,STOCK ACTUAL,PUNTO DE REORDENAMIENTO
2,POR_CATALOGAR_001,"Tuberia HDPE 200MM DN, Flanges Moviles C150, con perforaciones diam 76mm",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0
4,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0
5,11021056,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0
6,11010236,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,Unidades,NaN,0.0,0.0,0.0,50.0
9,11214458,TUBERIA HDPE 250 MM (10 pulgadas) PN20 CLASE 300 FF,PIPING,Unidades,NaN,0.0,0.0,0.0,75.0
...,...,...,...,...,...,...,...,...,...
363,11186861,"LAMPARA SOLAR;ROJA;0,220KG;280X85X80MM",SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,25.0
364,11184744,MANGUERAS DEPOSITACIÓN,SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,30.0
365,1190167,MANGUERA AGUA TTMGTPU3IN1M,SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,15.0
367,22003663,"DURMIENTE 6X9""X 1ml",SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,20.0
370,22002438,ANTICORROSIVO SPRAY; WD40,SERVICIOS GENERALES,unidades,NaN,0.0,0.0,0.0,50.0

In [70]:
stock[['STOCK INICIAL', 'INGRESOS', 'SALIDAS', 'STOCK ACTUAL', 'PUNTO DE REORDENAMIENTO']] = stock[['STOCK INICIAL', 'INGRESOS', 'SALIDAS', 'STOCK ACTUAL', 'PUNTO DE REORDENAMIENTO']].fillna(0)

## Estandarización unidades de medida y clasificación

In [71]:
stock['UM'].unique()

array(['Unidades', 'UNIDAD', 'kit', 'unidades', 'Bins', 'M2', 'Rollos',
       'M', 'kg', 'Mt', 'Kg', 'Metros', 'KIT', 'lts', 'mt', 'Unidad',
       'Bin', 'Rollo', 'saco 25 kg', 'Kit', 'metros'], dtype=object)

In [72]:
stock['CLASIFICACION'].unique()

array(['PIPING', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN',
       'PIEZÓMETROS', 'IMPERMEABILIAZACIÓN', 'OBRAS CIVILES',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA',
       'IMPERMEABILIZACIÓN LLAU-LLAU', 'TALLER BERLIAM',
       'PIEZAS ESPECIALIES', 'RIEGO MURO TRANQUE',
       'INSTRUMENTACIÓN GEOTECNICA'], dtype=object)

In [73]:
# Estandarización de categorías y unidades de medida
import sys
sys.path.append('..')
from src.data_process import estandarizar_datos

stock, valores_unicos_clasificacion, valores_unicos_um = estandarizar_datos(stock)

✅ Unidades estandarizadas
✅ Clasificación estandarizada

In [74]:
valores_unicos_clasificacion

array(['PIPING', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACION',
       'PIEZOMETROS', 'IMPERMEABILIZACION', 'OBRAS CIVILES',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA', 'TALLER BERLIAM',
       'RIEGO MURO TRANQUE', 'INSTRUMENTACION GEOTECNICA'], dtype=object)

In [75]:
valores_unicos_um

array(['UNIDAD', 'KIT', 'BIN', 'M2', 'ROLLO', 'M', 'KG', 'LT'],
      dtype=object)

# Carga

In [76]:
import sys
import sqlite3
sys.path.append('..')

from src.database import InventarioDatabase

# instanciamos la base de datos
db = InventarioDatabase('../src/db/inventario_lp02.db')
# Creamos la tabla insumos en la base de datos
conexion = sqlite3.connect('../src/db/inventario_lp02.db')
cursor = conexion.cursor()
cursor.execute('''
        CREATE TABLE IF NOT EXISTS stock (
            "CODIGO SAP"  TEXT NOT NULL PRIMARY KEY,
            "CLASIFICACION" TEXT NOT NULL,
            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,
            "UM" TEXT NOT NULL,
            "STOCK INICIAL" INTEGER NOT NULL,
            "INGRESOS" INTEGER NOT NULL,
            "SALIDAS" INTEGER NOT NULL,
            "STOCK ACTUAL" INTEGER NOT NULL,
            "PUNTO DE REORDENAMIENTO" INTEGER NOT NULL,
            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")
        )
    ''')
conexion.commit()
conexion.close()

In [77]:
for index, row in stock.iterrows():
    db.insert_stock(
        codigo_sap=row['CODIGO SAP'],
        clasificacion=row['CLASIFICACION'],
        descripcion=row['DESCRIPCION DEL MATERIAL'],
        um=row['UM'],
        stock_inicial=row['STOCK INICIAL'],
        ingreso=row['INGRESOS'],
        salida=row['SALIDAS'],
        stock_actual=row['STOCK ACTUAL'],
        punto_reordenamiento=row['PUNTO DE REORDENAMIENTO']
    )
db.close()

✓ stock con código SAP 11174821 insertado correctamente.
✓ stock con código SAP 11177716 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_001 insertado correctamente.
✓ stock con código SAP 11151921 insertado correctamente.
✓ stock con código SAP 11019704 insertado correctamente.
✓ stock con código SAP 11021056 insertado correctamente.
✓ stock con código SAP 11010236 insertado correctamente.
✓ stock con código SAP 11009715 insertado correctamente.
✓ stock con código SAP 11214480 insertado correctamente.
✓ stock con código SAP 11214458 insertado correctamente.
✓ stock con código SAP 11214215 insertado correctamente.
✓ stock con código SAP 11214116 insertado correctamente.
✓ stock con código SAP 11010503 insertado correctamente.
✓ stock con código SAP 11010504 insertado correctamente.
✓ stock con código SAP 11010505 insertado correctamente.
✓ stock con código SAP 11010506 insertado correctamente.
✓ stock con código SAP 11010507 insertado correctamente.
✓ stock con código SAP 11188680 insertado correctamente.

✓ stock con código SAP 11188679 insertado correctamente.
✓ stock con código SAP 11188678 insertado correctamente.
✓ stock con código SAP 11188677 insertado correctamente.
✓ stock con código SAP 11188676 insertado correctamente.
✓ stock con código SAP 11151922 insertado correctamente.
✓ stock con código SAP 11182677 insertado correctamente.
✓ stock con código SAP 11010715 insertado correctamente.
✓ stock con código SAP 11188664 insertado correctamente.
✓ stock con código SAP 11188663 insertado correctamente.
✓ stock con código SAP 11010713 insertado correctamente.
✓ stock con código SAP 11220106 insertado correctamente.
✓ stock con código SAP 11217090 insertado correctamente.
✓ stock con código SAP 11216847 insertado correctamente.
✓ stock con código SAP 11215311 insertado correctamente.
✓ stock con código SAP 11009709 insertado correctamente.
✓ stock con código SAP 11009710 insertado correctamente.
✓ stock con código SAP 11188685 insertado correctamente.
✓ stock con código SAP 11214913 insertado correctamente.
✓ stock con código SAP 11021475 insertado correctamente.
✓ stock con código SAP 11084585 insertado correctamente.
✓ stock con código SAP 11017599 insertado correctamente.
✓ stock con código SAP 11216764 insertado correctamente.
✓ stock con código SAP 11219398 insertado correctamente.
✓ stock con código SAP 11212167 insertado correctamente.
✓ stock con código SAP 11167363 insertado correctamente.
✓ stock con código SAP 11214659 insertado correctamente.
✓ stock con código SAP 11188697 insertado correctamente.
✓ stock con código SAP 11188696 insertado correctamente.
✓ stock con código SAP 11188695 insertado correctamente.
✓ stock con código SAP 11188694 insertado correctamente.
✓ stock con código SAP 11019705 insertado correctamente.
✓ stock con código SAP 11019706 insertado correctamente.
✓ stock con código SAP 12000972 insertado correctamente.
✓ stock con código SAP 11011495 insertado correctamente.
✓ stock con código SAP 11174494 insertado correctamente.
✓ stock con código SAP 11174493 insertado correctamente.
✓ stock con código SAP 11189653 insertado correctamente.
✓ stock con código SAP 11189652 insertado correctamente.
✓ stock con código SAP 11189651 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_002 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_003 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_004 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_005 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_006 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_007 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_008 insertado correctamente.
✓ stock con código SAP 11189647 insertado correctamente.
✓ stock con código SAP 11189646 insertado correctamente.
✓ stock con código SAP 11189645 insertado correctamente.
✓ stock con código SAP 11189644 insertado correctamente.
✓ stock con código SAP 11188675 insertado correctamente.
✓ stock con código SAP 11188674 insertado correctamente.
✓ stock con código SAP 11216848 insertado correctamente.
✓ stock con código SAP 11216460 insertado correctamente.
✓ stock con código SAP 11216462 insertado correctamente.
✓ stock con código SAP 11216344 insertado correctamente.
✓ stock con código SAP 11216345 insertado correctamente.
✓ stock con código SAP 11216830 insertado correctamente.
✓ stock con código SAP 11216347 insertado correctamente.
✓ stock con código SAP 11216349 insertado correctamente.
✓ stock con código SAP 11212162 insertado correctamente.
✓ stock con código SAP 11212171 insertado correctamente.
✓ stock con código SAP 11212174 insertado correctamente.
✓ stock con código SAP 11021639 insertado correctamente.
✓ stock con código SAP 11021637 insertado correctamente.
❌ Error de integridad: UNIQUE constraint failed: stock.CODIGO SAP
✓ stock con código SAP 11010463 insertado correctamente.
✓ stock con código SAP 11014385 insertado correctamente.
✓ stock con código SAP 11021151 insertado correctamente.
✓ stock con código SAP 11214515 insertado correctamente.
✓ stock con código SAP 11215312 insertado correctamente.
✓ stock con código SAP 11010379 insertado correctamente.
✓ stock con código SAP 11021150 insertado correctamente.
✓ stock con código SAP 11021149 insertado correctamente.
✓ stock con código SAP 11010237 insertado correctamente.
✓ stock con código SAP 11018390 insertado correctamente.
✓ stock con código SAP 11188692 insertado correctamente.
✓ stock con código SAP 11189133 insertado correctamente.
✓ stock con código SAP 11020650
 insertado correctamente.
✓ stock con código SAP 11016010 insertado correctamente.
✓ stock con código SAP 11010385 insertado correctamente.
✓ stock con código SAP 11014110 insertado correctamente.
✓ stock con código SAP 11188684 insertado correctamente.
✓ stock con código SAP 11188683 insertado correctamente.
✓ stock con código SAP 11188682 insertado correctamente.
✓ stock con código SAP 11188681 insertado correctamente.
✓ stock con código SAP 11214445 insertado correctamente.
✓ stock con código SAP 11214446 insertado correctamente.
✓ stock con código SAP 11214521 insertado correctamente.
✓ stock con código SAP 11214520 insertado correctamente.
✓ stock con código SAP 11214444 insertado correctamente.
✓ stock con código SAP 11218044 insertado correctamente.
✓ stock con código SAP 11212170 insertado correctamente.
✓ stock con código SAP 11212165 insertado correctamente.
✓ stock con código SAP 11219139 insertado correctamente.
✓ stock con código SAP 11219140 insertado correctamente.
✓ stock con código SAP 11219141 insertado correctamente.
✓ stock con código SAP 11219142 insertado correctamente.
✓ stock con código SAP 11219143 insertado correctamente.
✓ stock con código SAP 11219144 insertado correctamente.
✓ stock con código SAP 11219819 insertado correctamente.
✓ stock con código SAP 11219820 insertado correctamente.
✓ stock con código SAP 11219822 insertado correctamente.
✓ stock con código SAP 11221696 insertado correctamente.
✓ stock con código SAP 11221697 insertado correctamente.
✓ stock con código SAP 11221698 insertado correctamente.
✓ stock con código SAP 11221699 insertado correctamente.
✓ stock con código SAP 11221700 insertado correctamente.
✓ stock con código SAP 11221701 insertado correctamente.
✓ stock con código SAP 11221703 insertado correctamente.
✓ stock con código SAP 11222641 insertado correctamente.
✓ stock con código SAP 11220096 insertado correctamente.
✓ stock con código SAP 11220097 insertado correctamente.
✓ stock con código SAP 11220099 insertado correctamente.
✓ stock con código SAP 11220101 insertado correctamente.
✓ stock con código SAP 11216885 insertado correctamente.
✓ stock con código SAP 11217695 insertado correctamente.
✓ stock con código SAP 11217711 insertado correctamente.
✓ stock con código SAP 11221838 insertado correctamente.
✓ stock con código SAP 11014109 insertado correctamente.
✓ stock con código SAP 11014107 insertado correctamente.
✓ stock con código SAP 11014108 insertado correctamente.
✓ stock con código SAP 11014111 insertado correctamente.
✓ stock con código SAP 11014076 insertado correctamente.
✓ stock con código SAP 11189132 insertado correctamente.
✓ stock con código SAP 11189131 insertado correctamente.
✓ stock con código SAP 11189130 insertado correctamente.
✓ stock con código SAP 11189129 insertado correctamente.
✓ stock con código SAP 11189128 insertado correctamente.
✓ stock con código SAP 11189127 insertado correctamente.
✓ stock con código SAP 11189126 insertado correctamente.
✓ stock con código SAP 11189125 insertado correctamente.
✓ stock con código SAP 11213967 insertado correctamente.
✓ stock con código SAP 11213969 insertado correctamente.
✓ stock con código SAP 11213970 insertado correctamente.
✓ stock con código SAP 11213972 insertado correctamente.
✓ stock con código SAP 11213973 insertado correctamente.
✓ stock con código SAP 11014178 insertado correctamente.
✓ stock con código SAP 11014179 insertado correctamente.
✓ stock con código SAP 11020143 insertado correctamente.
✓ stock con código SAP 11020155 insertado correctamente.
✓ stock con código SAP 11188691 insertado correctamente.
✓ stock con código SAP 11188690 insertado correctamente.
✓ stock con código SAP 11188689 insertado correctamente.
✓ stock con código SAP 11189120 insertado correctamente.
✓ stock con código SAP 11188688 insertado correctamente.
✓ stock con código SAP 11188687 insertado correctamente.
✓ stock con código SAP 11188686 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_009 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_010 insertado correctamente.
✓ stock con código SAP 11215310 insertado correctamente.
✓ stock con código SAP 11018117 insertado correctamente.
✓ stock con código SAP 11023641 insertado correctamente.
✓ stock con código SAP 11189117 insertado correctamente.
✓ stock con código SAP 11189116 insertado correctamente.
✓ stock con código SAP 11189124 insertado correctamente.
✓ stock con código SAP 11189123 insertado correctamente.
✓ stock con código SAP 11188668 insertado correctamente.
✓ stock con código SAP 11188667 insertado correctamente.
✓ stock con código SAP 11188666 insertado correctamente.
✓ stock con código SAP 11188665 insertado correctamente.
✓ stock con código SAP 11214516 insertado correctamente.
✓ stock con código SAP 11217092 insertado correctamente.
✓ stock con código SAP 11217089 insertado correctamente.
✓ stock con código SAP 11218787 insertado correctamente.
✓ stock con código SAP 11218782 insertado correctamente.
✓ stock con código SAP 11218783 insertado correctamente.
✓ stock con código SAP 11218784 insertado correctamente.
✓ stock con código SAP 11220105 insertado correctamente.
✓ stock con código SAP 11220104 insertado correctamente.
✓ stock con código SAP 11220103 insertado correctamente.
✓ stock con código SAP 11220102 insertado correctamente.
✓ stock con código SAP 11220177 insertado correctamente.
✓ stock con código SAP 11220176 insertado correctamente.
✓ stock con código SAP 11220175 insertado correctamente.
✓ stock con código SAP 11220174 insertado correctamente.
✓ stock con código SAP 11220173 insertado correctamente.
✓ stock con código SAP 11220172 insertado correctamente.
✓ stock con código SAP 11010962 insertado correctamente.
✓ stock con código SAP 11178700 insertado correctamente.
✓ stock con código SAP 11178702 insertado correctamente.
✓ stock con código SAP 11010277 insertado correctamente.
✓ stock con código SAP 11117559 insertado correctamente.
✓ stock con código SAP 11211977 insertado correctamente.
✓ stock con código SAP 11087505 insertado correctamente.
✓ stock con código SAP 11019229 insertado correctamente.
✓ stock con código SAP 11019154 insertado correctamente.
✓ stock con código SAP 88000142 insertado correctamente.
✓ stock con código SAP 11015103 insertado correctamente.
✓ stock con código SAP 11013752 insertado correctamente.
✓ stock con código SAP 11010239 insertado correctamente.
✓ stock con código SAP 11013747 insertado correctamente.
✓ stock con código SAP 11017089 insertado correctamente.
✓ stock con código SAP 88000081 insertado correctamente.
✓ stock con código SAP 12000774 insertado correctamente.
✓ stock con código SAP 12010335 insertado correctamente.
✓ stock con código SAP 12010336 insertado correctamente.
✓ stock con código SAP 11008954 insertado correctamente.
✓ stock con código SAP 11010243 insertado correctamente.
✓ stock con código SAP 11020115 insertado correctamente.
✓ stock con código SAP 11013029 insertado correctamente.
✓ stock con código SAP 11013030 insertado correctamente.
✓ stock con código SAP 11084547 insertado correctamente.
✓ stock con código SAP 12004083 insertado correctamente.
✓ stock con código SAP 88000184 insertado correctamente.
✓ stock con código SAP 11015895 insertado correctamente.
✓ stock con código SAP 11020020 insertado correctamente.
✓ stock con código SAP 11183480 insertado correctamente.
✓ stock con código SAP 11183481 insertado correctamente.
✓ stock con código SAP 11216762 insertado correctamente.
✓ stock con código SAP 22003670 insertado correctamente.
✓ stock con código SAP 22003671 insertado correctamente.
✓ stock con código SAP 22002942 insertado correctamente.
✓ stock con código SAP 11019133 insertado correctamente.
✓ stock con código SAP 22003422 insertado correctamente.
✓ stock con código SAP 11021401 insertado correctamente.
✓ stock con código SAP 11021398 insertado correctamente.
✓ stock con código SAP 11020376 insertado correctamente.
✓ stock con código SAP 11021399 insertado correctamente.
✓ stock con código SAP 11019722 insertado correctamente.
✓ stock con código SAP 22002945 insertado correctamente.
✓ stock con código SAP 22003216 insertado correctamente.
✓ stock con código SAP 11090702 insertado correctamente.
✓ stock con código SAP 22003316 insertado correctamente.
✓ stock con código SAP 22003115 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_011 insertado correctamente.
✓ stock con código SAP 22003362 insertado correctamente.
✓ stock con código SAP 22002944 insertado correctamente.
✓ stock con código SAP 22002769 insertado correctamente.
✓ stock con código SAP 22003213 insertado correctamente.
✓ stock con código SAP 22003042 insertado correctamente.
✓ stock con código SAP 22003685 insertado correctamente.
✓ stock con código SAP 22003317 insertado correctamente.
✓ stock con código SAP 22003877 insertado correctamente.
✓ stock con código SAP 11187366 insertado correctamente.
✓ stock con código SAP 22003363 insertado correctamente.
✓ stock con código SAP 22003318 insertado correctamente.
✓ stock con código SAP 22003208 insertado correctamente.
✓ stock con código SAP 11220181 insertado correctamente.
✓ stock con código SAP 11220180 insertado correctamente.
✓ stock con código SAP 11219877 insertado correctamente.
✓ stock con código SAP 11220121 insertado correctamente.
✓ stock con código SAP 22003058 insertado correctamente.
✓ stock con código SAP 22002973 insertado correctamente.
✓ stock con código SAP 22011463 insertado correctamente.
✓ stock con código SAP 22002943 insertado correctamente.
✓ stock con código SAP 22003212 insertado correctamente.
✓ stock con código SAP 22003424 insertado correctamente.
✓ stock con código SAP 22000311 insertado correctamente.
✓ stock con código SAP 11216124 insertado correctamente.
✓ stock con código SAP 11216642 insertado correctamente.
✓ stock con código SAP 22002772 insertado correctamente.
✓ stock con código SAP 22003768 insertado correctamente.
✓ stock con código SAP 11021075 insertado correctamente.
✓ stock con código SAP 22003464 insertado correctamente.
✓ stock con código SAP 11017558 insertado correctamente.
✓ stock con código SAP 11016400 insertado correctamente.
✓ stock con código SAP 11010217 insertado correctamente.
✓ stock con código SAP 11127227 insertado correctamente.
✓ stock con código SAP 11019047 insertado correctamente.
✓ stock con código SAP 11180037 insertado correctamente.
✓ stock con código SAP 11188671 insertado correctamente.
✓ stock con código SAP 11188670 insertado correctamente.
✓ stock con código SAP 11188669 insertado correctamente.
✓ stock con código SAP 44001452 insertado correctamente.
✓ stock con código SAP 11220570 insertado correctamente.
✓ stock con código SAP 11215167 insertado correctamente.
✓ stock con código SAP 11167118 insertado correctamente.
✓ stock con código SAP 11012101 insertado correctamente.
✓ stock con código SAP 11019976 insertado correctamente.
✓ stock con código SAP 11012103 insertado correctamente.
✓ stock con código SAP 11012180 insertado correctamente.
✓ stock con código SAP 22003324 insertado correctamente.
✓ stock con código SAP 11017598 insertado correctamente.
✓ stock con código SAP 22015853 insertado correctamente.
✓ stock con código SAP 11018319 insertado correctamente.
✓ stock con código SAP 22015666 insertado correctamente.
✓ stock con código SAP 11009707 insertado correctamente.
✓ stock con código SAP 11019930 insertado correctamente.
✓ stock con código SAP 11185704 insertado correctamente.
✓ stock con código SAP 22015864 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_012 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_013 insertado correctamente.
✓ stock con código SAP 22003330 insertado correctamente.
✓ stock con código SAP 22003328 insertado correctamente.
✓ stock con código SAP 11015725 insertado correctamente.
✓ stock con código SAP 11015724 insertado correctamente.
✓ stock con código SAP 11014419 insertado correctamente.
✓ stock con código SAP 22007412 insertado correctamente.
✓ stock con código SAP 22007414 insertado correctamente.
✓ stock con código SAP 22007415 insertado correctamente.
✓ stock con código SAP 22007416 insertado correctamente.
✓ stock con código SAP 22003326 insertado correctamente.
✓ stock con código SAP 22003997 insertado correctamente.
✓ stock con código SAP 22010344 insertado correctamente.
✓ stock con código SAP 22015472 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_014 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_015 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_016 insertado correctamente.
✓ stock con código SAP 11189121 insertado correctamente.
✓ stock con código SAP 22010346 insertado correctamente.
✓ stock con código SAP 22010348 insertado correctamente.
✓ stock con código SAP 22010345 insertado correctamente.
✓ stock con código SAP 44002471 insertado correctamente.
✓ stock con código SAP 22015855 insertado correctamente.
✓ stock con código SAP 22003331 insertado correctamente.
✓ stock con código SAP 11188495 insertado correctamente.
✓ stock con código SAP 11188673 insertado correctamente.
✓ stock con código SAP 11188672 insertado correctamente.
✓ stock con código SAP 11214401 insertado correctamente.
✓ stock con código SAP 11179000 insertado correctamente.
✓ stock con código SAP 11215498 insertado correctamente.
✓ stock con código SAP 11176304 insertado correctamente.
✓ stock con código SAP 11186792 insertado correctamente.
✓ stock con código SAP 12001131 insertado correctamente.
✓ stock con código SAP 11176305 insertado correctamente.
✓ stock con código SAP 11184744 insertado correctamente.
❌ Error de integridad: UNIQUE constraint failed: stock.CODIGO SAP
✓ stock con código SAP 44001533 insertado correctamente.
✓ stock con código SAP 44002047 insertado correctamente.
✓ stock con código SAP 22010349 insertado correctamente.
✓ stock con código SAP 22003662 insertado correctamente.
✓ stock con código SAP 22003658 insertado correctamente.
✓ stock con código SAP 22003657 insertado correctamente.
✓ stock con código SAP 22004051 insertado correctamente.
✓ stock con código SAP 22004049 insertado correctamente.
✓ stock con código SAP 22004050 insertado correctamente.
✓ stock con código SAP 22004048 insertado correctamente.
✓ stock con código SAP 22003329 insertado correctamente.
✓ stock con código SAP 44000151 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_017 insertado correctamente.
✓ stock con código SAP 22003591 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_018 insertado correctamente.
✓ stock con código SAP 22007382 insertado correctamente.
✓ stock con código SAP 11215216 insertado correctamente.
✓ stock con código SAP 11021059 insertado correctamente.
✓ stock con código SAP 11214644 insertado correctamente.
✓ stock con código SAP 22003321 insertado correctamente.
✓ stock con código SAP POR_CATALOGAR_019 insertado correctamente.
✓ stock con código SAP 11020112 insertado correctamente.
✓ stock con código SAP 22004102 insertado correctamente.
✓ stock con código SAP 22003428 insertado correctamente.
✓ stock con código SAP 11171151 insertado correctamente.
✓ stock con código SAP 11186859 insertado correctamente.
✓ stock con código SAP 11186860 insertado correctamente.
✓ stock con código SAP 11186861 insertado correctamente.
❌ Error de integridad: UNIQUE constraint failed: stock.CODIGO SAP

In [78]:
# import sqlite3
conexion = sqlite3.connect('../src/db/inventario_lp02.db')
cursor = conexion.cursor()
cursor.execute("SELECT * FROM sqlite_master")
consulta = cursor.fetchall()
# tablas = pd.read_sql_query("DROP TABLE stock", conexion)
conexion.close()
consulta

[('table',
  'sqlite_sequence',
  'sqlite_sequence',
  18,
  'CREATE TABLE sqlite_sequence(name,seq)'),
 ('table',
  'insumos',
  'insumos',
  2,
  'CREATE TABLE insumos (\n            "CODIGO SAP" TEXT PRIMARY KEY,\n            "DESCRIPCION DEL MATERIAL" TEXT,\n            "CLASIFICACION" TEXT,\n            "UM" TEXT,\n            "OBSERVACIONES" TEXT\n        )'),
 ('index', 'sqlite_autoindex_insumos_1', 'insumos', 3, None),
 ('table',
  'ingresos',
  'ingresos',
  7,
  'CREATE TABLE ingresos (\n            "ID" INTEGER PRIMARY KEY AUTOINCREMENT,\n            "CODIGO SAP" TEXT NOT NULL,\n            "CLASIFICACION" TEXT NOT NULL,\n            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,\n            "UM" TEXT NOT NULL,\n            "CANTIDAD" INTEGER NOT NULL,\n            "FECHA DE INGRESO" DATE NOT NULL,\n            "RESERVA" TEXT,\n            "GUIA DESPACHO" TEXT,\n            "OC" TEXT,\n            "USO: OPERACIONES/PROYECTO" TEXT,\n            "RECIBIDO POR" TEXT,\n            "UBICACION" TEXT,\n            "EMPRESA" TEXT,\n            "PRECIO UNITARIO" REAL,\n            "OBSERVACIONES" TEXT,\n            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")\n        )'),
 ('table',
  'salidas',
  'salidas',
  9,
  'CREATE TABLE salidas (\n            "ID" INTEGER PRIMARY KEY AUTOINCREMENT,\n            "CODIGO SAP" TEXT NOT NULL,\n            "CLASIFICACION" TEXT NOT NULL,\n            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,\n            "UM" TEXT NOT NULL,\n            "CANTIDAD" INTEGER NOT NULL,\n            "FECHA DE SALIDA" DATE NOT NULL,\n            "N° DE GUIA DE SALIDA" TEXT,\n            "USO: OPERACIONES/PROYECTO" TEXT,\n            "ENTREGADO A" TEXT,\n            "COMENTARIOS" TEXT,\n            "UBICACION DE RETIRO" TEXT,\n            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")\n        )'),
 ('table',
  'stock',
  'stock',
  13,
  'CREATE TABLE stock (\n            "CODIGO SAP"  TEXT NOT NULL PRIMARY KEY,\n            "CLASIFICACION" TEXT NOT NULL,\n            "DESCRIPCION DEL MATERIAL" TEXT NOT NULL,\n            "UM" TEXT NOT NULL,\n            "STOCK INICIAL" INTEGER NOT NULL,\n            "INGRESOS" INTEGER NOT NULL,\n            "SALIDAS" INTEGER NOT NULL,\n            "STOCK ACTUAL" INTEGER NOT NULL,\n            "PUNTO DE REORDENAMIENTO" INTEGER NOT NULL,\n            FOREIGN KEY("CODIGO SAP") REFERENCES insumos("CODIGO SAP")\n        )'),
 ('index', 'sqlite_autoindex_stock_1', 'stock', 14, None)]